format = """
$character\
$directory\
$git_branch\
$git_status\
$python"""

add_newline = false

[character]
success_symbol = "[âžœ](bold green) "
error_symbol = "[âžœ](bold red) "

[directory]
truncation_length = 1
read_only = ' ðŸ”’'

[git_branch]
symbol = 'git'
format = '[$symbol:\([$branch](bold red)\)](bold blue) '

[git_status]
style = "bold yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
