# =============================================================================
# Golang üêπ
# =============================================================================

[[language]]
name = "go"
auto-format = true
formatter = ["goimports"]
language-servers = [ "gopls", "golangci-lint-lsp" ]

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[[language]]
name = "templ"
auto-format = true

# =============================================================================
# Python üêç
# =============================================================================
# 
[language-server.basedpyright]
except-features = ["format", "code-action"]



[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.basedpyright.config.basedpyright.analysis]
autoSearchPaths = true
typeCheckingMode = "standard"
diagnosticMode = "openFilesOnly"
autoImportCompletions = true

[language-server.ruff.config.settings]
# logLevel = "debug"
configuration = "~/.config/ruff/ruff.toml"

[[language]]
name = "python"
language-id = "python"
roots = ["pyproject.toml", "poetry.lock", ".git", ".venv/"]
language-servers = ["ruff", "basedpyright" ]
auto-format = true
file-types = ["py", "ipynb"]
# comment-token = "#"
# shebangs = ["python"]

# =============================================================================
# Frontend üåê
# =============================================================================
# 
[language-server]
emmet-ls = { command = "emmet-ls", args = [ "--stdio" ]}
biome = { command = "biome", args = ["lsp-proxy"] }
tailwindcss = { command = "tailwind-css-language-server", args = ["--stdio"] }

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = false }

[language-server.vscode-css-language-server.config]
css = { validate = { enable = true } }
scss = { validate = { enable = true } }
less = { validate = { enable = true } }
provideFormatter = true

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "emmet-ls", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "emmet-ls", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "eslint", "emmet-ls", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "eslint", "emmet-ls", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "eslint", "emmet-ls", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "eslint", "emmet-ls", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

# =============================================================================
# JSON 
# =============================================================================

[language-server.vscode-json]
command = "vscode-json-language-server"
args = ["--stdio"]

[language-server.vscode-json.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

# =============================================================================
# Database üíΩ
# =============================================================================

[[language]]
name = "prisma"
language-servers = ["prisma-language-server"]
auto-format = true

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
# language-servers = ["sql-language-server"]
formatter = { command = "pg_format", args = ["-"] }
auto-format = true

# =============================================================================
# Markdown üéØ
# =============================================================================
 
[[language]]
name = "markdown"
text-width = 80
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["marksman"]
formatter = { command = 'prettier', args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "never", # <always|never|preserve>
] }
auto-format = true

# =============================================================================
# Other
# =============================================================================

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "lua"
formatter = { command = "stylua", args = [ "-" ] }
auto-format = true
