# inherits = "autumn"
# inherits = "aura-dark"
# inherits = "tokyonight_storm"
inherits = "github_dark"

"ui.background" = {}
"ui.gutter" = {}
"ui.statusline" = {}

# Aura only
# "ui.cursorline" = { bg = "accent33"}

# Autumn only

# "ui.linenr" = { fg = "my_gray5" }
